In [1]:
import numpy as np

In [78]:
#Set values
T = 3 #temperature
J = 1 #interaction energy
h = 0 #external magnetic field
kb = 1 #Boltzmann constant
iterate = 10


#Initial State
L = 3 #square side length
S = np.random.choice([1,-1],size=[L,L])
i = 0

while i < iterate:
    i += 1
    
    #Choosing a lattice site
    x = np.random.randint(0,L)
    y = np.random.randint(0,L)
    Si = S[x,y]
    
    #Calculating energy change while maintaining periodicity of lattice (boundary condition)
    hi = J*(S[(x+1)%L,y]+S[(x-1)%L,y]+S[x,(y+1)%L]+S[x,(y-1)%L])+h
    E = -2*Si*hi
    
    if E >= 0:
        Si = -Si
    else:
        r = np.random.random()
        if r < np.exp(E/kb/T):
            Si = -Si
        else: 
            Si = Si
    

In [81]:
S1 = np.random.choice([1,-1],size=[L,L])
S2 = np.ones((L, L))
print(S1, S2)

[[ 1  1  1]
 [-1 -1  1]
 [-1 -1 -1]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Varying T

In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 20 23:07:02 2018

@author: Mary
"""
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.animation as animation

fig, ax = plt.subplots()

#Set values
J = 1 #interaction energy
h = 0 #external magnetic field
kb = 1 #Boltzmann constant
Tc = 2.269*J/kb
T = Tc*0.3 #temperature
iterate = 100000

"""
T = Tc: 
self-similar, clusters of parallel spins show up at all scales
correctional length: L
lattice constant << r = |ri-rj| << L: <SiSj> decay as a power of r

T = 0.8Tc:
system is magnetized
Spontanerous fluctuations: magnet has chosen one of the 2 possible directions:
    Si are aligned parallel to this direction: Nonzero spontaneous magnetization
    
At low T: 
time is estimated using Arrhenius' Law
To change sign of sum(Si): Energy barrier of JL is scaled
A wall of positive and negative magnatization has to form, which diffuses through lattice
No reversal of magnetization at T = J/kb

T = 1.5Tc:
spin is distributed randomly
correlational length reaches lattice constant
generate regions with positive and negative magnetization

T<Tc:
positive and negative magnetization
Diffusin domain walls which anihilate each other or contract until thermal equi is reached

T=Tc:
magnetization exhibits strong fluctuation as a function of time
"""

#Initial State
L = 100 #square side length
S = np.random.choice([1,-1],size=[L,L])
#S = np.ones((L, L))
i = 0
x,y = 0,0
ims = []
temp = np.array(np.linspace(0,10,iterate))
#Fig 3 low to high


while i < iterate:
    T = temp[i]
    if i%200 == 0:
        magnetization = np.sum(S)/L/L
        #im = ax.matshow(S, cmap=plt.cm.Blues)
        #t = ax.annotate('M = ' + str(magnetization) + 'T = ' + str(T), (0,0))
        #ims.append([im,t])
        print(i, magnetization)#,'(',x,y,')')
    
    #Choosing a lattice site
    x = np.random.randint(0,L)
    y = np.random.randint(0,L)
    Si = S[x,y]
    
    #Calculating energy change while maintaining periodicity of lattice (boundary condition)
    hi = J*(S[(x+1)%L,y]+S[(x-1)%L,y]+S[x,(y+1)%L]+S[x,(y-1)%L])+h
    E = -2*Si*hi
    
    if E >= 0:
        S[x,y] = -Si
    else:
        r = np.random.random()
        if r < np.exp(E/kb/T):
            S[x,y] = -Si
        else: 
            S[x,y] = Si
    i += 1

ax.matshow(S, cmap=plt.cm.Blues)
plt.axis('off')   
#ani = animation.ArtistAnimation(fig, ims, blit=False)
#mywriter = animation.FFMpegWriter(fps=1)
#plt.show(mywriter)

Varying h

In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 20 23:07:02 2018

@author: Mary
"""
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.animation as animation

fig, ax = plt.subplots()

#Set values
J = 1 #interaction energy
h = 0 #external magnetic field
kb = 1 #Boltzmann constant
Tc = 2.269*J/kb
T = Tc*0.3 #temperature
iterate = 100000

"""
T = Tc: 
self-similar, clusters of parallel spins show up at all scales
correctional length: L
lattice constant << r = |ri-rj| << L: <SiSj> decay as a power of r

T = 0.8Tc:
system is magnetized
Spontanerous fluctuations: magnet has chosen one of the 2 possible directions:
    Si are aligned parallel to this direction: Nonzero spontaneous magnetization
    
At low T: 
time is estimated using Arrhenius' Law
To change sign of sum(Si): Energy barrier of JL is scaled
A wall of positive and negative magnatization has to form, which diffuses through lattice
No reversal of magnetization at T = J/kb

T = 1.5Tc:
spin is distributed randomly
correlational length reaches lattice constant
generate regions with positive and negative magnetization

T<Tc:
positive and negative magnetization
Diffusin domain walls which anihilate each other or contract until thermal equi is reached

T=Tc:
magnetization exhibits strong fluctuation as a function of time
"""

#Initial State
L = 100 #square side length
S = np.random.choice([1,-1],size=[L,L])
#S = np.ones((L, L))
i = 0
x,y = 0,0
ims = []
temp = np.array(np.linspace(0,10,iterate))
#Fig 3 low to high


while i < iterate:
    T = temp[i]
    if i%200 == 0:
        magnetization = np.sum(S)/L/L
        #im = ax.matshow(S, cmap=plt.cm.Blues)
        #t = ax.annotate('M = ' + str(magnetization) + 'T = ' + str(T), (0,0))
        #ims.append([im,t])
        print(i, magnetization)#,'(',x,y,')')
    
    #Choosing a lattice site
    x = np.random.randint(0,L)
    y = np.random.randint(0,L)
    Si = S[x,y]
    
    #Calculating energy change while maintaining periodicity of lattice (boundary condition)
    hi = J*(S[(x+1)%L,y]+S[(x-1)%L,y]+S[x,(y+1)%L]+S[x,(y-1)%L])+h
    E = -2*Si*hi
    
    if E >= 0:
        S[x,y] = -Si
    else:
        r = np.random.random()
        if r < np.exp(E/kb/T):
            S[x,y] = -Si
        else: 
            S[x,y] = Si
    i += 1

ax.matshow(S, cmap=plt.cm.Blues)
plt.axis('off')   
#ani = animation.ArtistAnimation(fig, ims, blit=False)
#mywriter = animation.FFMpegWriter(fps=1)
#plt.show(mywriter)

Ising Animation

In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 20 23:07:02 2018

@author: Mary
"""
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.animation as animation

fig, ax = plt.subplots()


"""
Onsager solution:
Beta = 1/8
v=1
gamma = 7/4
alpha = 0

h=0 
infinite system in 2d has a phase transition 
T<Tc: spins parallel to each other in thermal average 
energy is symmetric in M: Spontaneous Symmetry Breaking

h!=0
cancel symmetry
destrors phase transition

Phase transition:
T increases: Magnetization approaches 0 for T>= Tc


T = Tc: 
self-similar, clusters of parallel spins show up at all scales
correctional length: L
lattice constant << r = |ri-rj| << L: <SiSj> decay of the spins as a power of r

T = 0.8Tc:
system is magnetized
Spontanerous fluctuations: magnet has chosen one of the 2 possible directions:
    Si are aligned parallel to this direction: Nonzero spontaneous magnetization
    
At low T: 
time is estimated using Arrhenius' Law
To change sign of sum(Si): Energy barrier of JL is scaled
A wall of positive and negative magnatization has to form, which diffuses through lattice
No reversal of magnetization at T = J/kb

T = 1.5Tc:
spin is distributed randomly
correlational length reaches lattice constant
generate regions with positive and negative magnetization

T<Tc:
positive and negative magnetization
Diffusin domain walls which anihilate each other or contract until thermal equi is reached

T=Tc:
magnetization exhibits strong fluctuation as a function of time
"""
#Set values
J = 1 #interaction energy
h = 1 #external magnetic field
kb = 1 #Boltzmann constant
Tc = 2.269*J/kb
T = Tc*0.3 #temperature
iterate = 100000

#Initial State
L = 100 #square side length
#S = np.random.choice([1,-1],size=[L,L])
S = 1*np.ones((L, L))
i = 0
x,y = 0,0
ims = []

ax.matshow(S, cmap=plt.cm.Blues)

while i < iterate:
    i += 1
    if i%200 == 0:
        magnetization = np.sum(S)/L/L
        #im = ax.matshow(S, cmap=plt.cm.Blues)
        #t = ax.annotate('M = ' + str(magnetization), (0,0))
        #ims.append([im,t])
        print(i, magnetization)#,'(',x,y,')')
    
    #Choosing a lattice site
    x = np.random.randint(0,L)
    y = np.random.randint(0,L)
    Si = S[x,y]
    
    #Calculating energy change while maintaining periodicity of lattice (boundary condition)
    hi = J*(S[(x+1)%L,y]+S[(x-1)%L,y]+S[x,(y+1)%L]+S[x,(y-1)%L])+h
    E = -2*Si*hi
    
    if E >= 0:
        S[x,y] = -Si
    else:
        r = np.random.random()
        if r < np.exp(E/kb/T):
            S[x,y] = -Si
        else: 
            S[x,y] = Si

#ax.matshow(S, cmap=plt.cm.Blues)
plt.axis('off')   
#ani = animation.ArtistAnimation(fig, ims, blit=False)
#mywriter = animation.FFMpegWriter(fps=1)
#plt.show(mywriter)